export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_FULFILLED = 'GET_DEVICES_FULFILLED';
export const GET_DEVICES_PENDING = 'GET_DEVICES_PENDING';
export const GET_DEVICES_REJECTED = 'GET_DEVICES_REJECTED';
