export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_FULFILLED = 'GET_DEVICES_FULFILLED';
export const GET_DEVICES_PENDING = 'GET_DEVICES_PENDING';
export const GET_DEVICES_REJECTED = 'GET_DEVICES_REJECTED';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';

export const LEARN_COMMAND = 'LEARN_COMMAND';
export const LEARN_COMMAND_FULFILLED = 'LEARN_COMMAND_FULFILLED';
export const LEARN_COMMAND_PENDING = 'LEARN_COMMAND_PENDING';
export const LEARN_COMMAND_REJECTED = 'LEARN_COMMAND_REJECTED';

export const SEND_COMMAND = 'SEND_COMMAND';
export const SEND_COMMAND_FULFILLED = 'SEND_COMMAND_FULFILLED';
export const SEND_COMMAND_PENDING = 'SEND_COMMAND_PENDING';
export const SEND_COMMAND_REJECTED = 'SEND_COMMAND_REJECTED';

export const DELETE_COMMAND = 'DELETE_COMMAND';
export const DELETE_COMMAND_FULFILLED = 'DELETE_COMMAND_FULFILLED';
export const DELETE_COMMAND_PENDING = 'DELETE_COMMAND_PENDING';
export const DELETE_COMMAND_REJECTED = 'DELETE_COMMAND_REJECTED';
